# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrZqU_Vc85JHCvRYRYpHuvjcc15R5074
"""

import streamlit as st
import numpy as np
import tensorflow as tf
from PIL import Image
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# ==============================
# KONFIGURASI HALAMAN
# ==============================
st.set_page_config(
    page_title="Klasifikasi Daun Herbal",
    page_icon="🌿",
    layout="centered"
)

st.title("🌿 Klasifikasi Daun Herbal Tradisional")
st.write("Upload gambar daun untuk mengetahui **nama tanaman dan khasiatnya**")

# ==============================
# LOAD MODEL
# ==============================
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("mobilenetv2_daun_herbal_lontar.h5")

model = load_model()

# ==============================
# CLASS NAMES (HARUS SESUAI TRAINING)
# ==============================
class_names = [
    'AwarAwar', 'Cemara', 'Delima', 'JambuBiji', 'Jeruk',
    'Kelor', 'Mangga', 'Pepaya', 'Salam', 'Sirih', 'Sirsak'
]

# ==============================
# KHASIAT TANAMAN
# ==============================
khasiat = {
    'AwarAwar': 'Mengatasi peradangan, mempercepat penyembuhan luka.',
    'Cemara': 'Meredakan batuk, menghangatkan tubuh.',
    'Delima': 'Antioksidan tinggi, meningkatkan imunitas.',
    'JambuBiji': 'Mengatasi diare, meningkatkan daya tahan tubuh.',
    'Jeruk': 'Sumber vitamin C, meningkatkan kekebalan tubuh.',
    'Kelor': 'Menurunkan kolesterol, antioksidan alami.',
    'Mangga': 'Melancarkan pencernaan, kaya vitamin A.',
    'Pepaya': 'Melancarkan pencernaan, mengatasi sembelit.',
    'Salam': 'Menurunkan gula darah, melancarkan pencernaan.',
    'Sirih': 'Antiseptik alami, mengatasi bau mulut.',
    'Sirsak': 'Meningkatkan imunitas, antioksidan.'
}

# ==============================
# FUNGSI PREDIKSI
# ==============================
def predict_image(img):
    img = img.convert('RGB').resize((224, 224))
    img_array = np.array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)

    preds = model.predict(img_array)[0]
    idx = np.argmax(preds)
    confidence = preds[idx] * 100

    return class_names[idx], confidence

# ==============================
# UPLOAD GAMBAR
# ==============================
uploaded_file = st.file_uploader(
    "📷 Upload gambar daun",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file)

    st.image(image, caption="Gambar yang diunggah", use_column_width=True)

    with st.spinner("🔍 Menganalisis gambar..."):
        label, confidence = predict_image(image)

    st.success(f"🌱 **Prediksi:** {label}")
    st.info(f"🎯 **Confidence:** {confidence:.2f}%")

    if confidence < 60:
        st.warning("⚠️ Model kurang yakin terhadap prediksi ini.")
    else:
        st.subheader("💊 Khasiat Tanaman")
        st.write(khasiat.get(label, "Khasiat belum tersedia."))

# ==============================
# FOOTER
# ==============================
st.markdown("---")
st.caption("Aplikasi Klasifikasi Daun Herbal • MobileNetV2")
